name: publish openwrt-toolchian 19.07.1 to github registry


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
    push:
        branches:
            - openwrt-toolchians-19.07.1

jobs:
    publish_image:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '[BuildGhrc]')"
        permissions:
          contents: read
          packages: write

        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              type=ref,event=branch
              type=sha
    
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: Dockerfile
            push: true
            tags: |
                ${{ steps.meta.outputs.tags }}
                ghcr.io/haldir65/upgraded-train:openwrt-19.07.1
            labels: ${{ steps.meta.outputs.labels }} 