name: build h2o server

on:
    workflow_dispatch:



jobs:        
  buildH2oServer:
    name: Build h2o server
    continue-on-error: false
    strategy:
      matrix:
        target:
          - id: 'linux-amd64'
            os: 'ubuntu-latest'
          - id: 'darwin-amd64'
            # os: 'macos-14-xlarge' ## failed
            os: 'macos-14'
      fail-fast: true

    runs-on: ${{ matrix.target.os }}    

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
            fetch-depth: 2

      - name: Install `deps` on Ubuntu
        if: startsWith(matrix.target.id, 'linux-')
        shell: bash
        run: |
          sudo apt install ninja-build build-essential autoconf automake tree clang cmake coreutils libidn2-0-dev pkg-config -y
          echo "cpu core num is "
          nproc
      
      - name: Install `ninja llvm cmake `  on macOS
        if: startsWith(matrix.target.id, 'darwin-')
        shell: bash
        run: |
          brew install ninja llvm cmake tree libunistring libidn2 pkg-config autoconf automake libtool
          clang --version
          echo "BREW_INSTALL_PREFIX=$(brew --prefix llvm)" >> $GITHUB_ENV
          echo "${BREW_INSTALL_PREFIX}/bin"
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
          clang --version
          echo "llvm"
          /opt/homebrew/opt/llvm/bin/clang --version


      - name: test deps
        if: startsWith(matrix.target.id, 'darwin-') || startsWith(matrix.target.id, 'linux-')
        shell: bash
        run: |
          uname -a
          clang --version
          clang++ --version

      - name: build h2o server
        shell: bash
        run: |
          bash scripts/build_h2o.sh
     
      - name: show layouts
        shell: bash
        run: |
            tree -L 2
            ls -al
    
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.id }}-${{ matrix.target.os }}-prebuilt
          path: dist
          if-no-files-found: error
          retention-days: 7


  