name: build openwrt-toolchian 19.07.1

on:
    workflow_dispatch:
    push:
      branches:
        - openwrt-toolchians-19.07.1


env:
    REGISTRY_IMAGE: haldir65/hello-docker-hub
    DH_UNAME: haldir65
    IMAG_TAG: openwrt-toolchians-19.07.1

jobs:
    build:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '[BuildDocker-toolchains]')"
        strategy:
            fail-fast: false
            matrix:
                platform:
                - linux/amd64
        steps:
        -   name: Prepare
            run: |
                platform=${{ matrix.platform }}
                echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          

        -   name: Checkout
            uses: actions/checkout@v4    
                
        -   name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ env.REGISTRY_IMAGE }}
        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ env.DH_UNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

        -   name: Build and push 
            id: build
            uses: docker/build-push-action@v5
            with:
                context: .
                file: Dockerfile
                push: true
                platforms: ${{ matrix.platform }}
                labels: ${{ steps.meta.outputs.labels }}
                build-args: |
                    BUILDPLATFORM=${{ matrix.platform }}
            
 