name: testing llvm toolchain

on:
    workflow_dispatch:
    push:
      branches:
        - test_clang_chain

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    continue-on-error: false
    strategy:
      matrix:
        target:
          - id: 'linux-amd64'
            os: 'ubuntu-latest'
            tar_extra_args: ''
            llvm_version: '18.x'
          # - id: 'linux-aarch64'
          #   os: "ubuntu-latest" 
          #  os: ['self-hosted', 'linux', 'ARM64']
          # - id: 'linux-riscv64'
          #   os: "ubuntu-latest"
          #  os: ['self-hosted', 'linux', 'RISCV64']
          ## https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
        #   - id: 'darwin-amd64'
        #     os: 'macos-14'
        #     tar_extra_args: ''
        #     llvm_version: '18.x'
        #   - id: 'windows-amd64'
        #     os: 'windows-2022'
        #     llvm_version: '16.x'
        #   # When unpacking an archive on Windows, the symlinks can't be
        #   # created unless the target path already exists. This causes
        #   # problems when the linked file is ordered after the link
        #   # inside the archive. Dereferencing the files when packing them
        #   # adds an additional copy per link, but it reliably works and
        #   # the additional size is not too large on Windows.
        #     tar_extra_args: '--dereference'
        # # llvm_version: ['17.x']
        # llvm_repo_url: ['https://github.com/llvm/llvm-project.git']
      fail-fast: true

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
            fetch-depth: 2
      - name: Install `ninja` on Ubuntu
        if: startsWith(matrix.target.id, 'linux-')
        shell: bash
        run: |
          sudo apt install ninja-build build-essential clang coreutils tree -y
          echo "cpu core num is "
          nproc
      

      - name: test
        if: matrix.target.id == 'linux-amd64'
        shell: bash
        run: |
          gh run download 8126334463
          pwd
          tree -L 3
          cd linux-amd64-ubuntu-latest-18.x
          tar -xf llvm.tar.xz
          cd ..
          mv linux-amd64-ubuntu-latest-18.x llvm-project 
          bash ./scripts/build_fmt.sh
