name: Publish image to Docker hub
on:
    workflow_dispatch:
    push:
        branches:
            - build_and_publish_docker

env:
  REGISTRY_IMAGE: haldir65/hello-docker-hub

jobs:
    publish_image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: haldir65
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              ${{ env.REGISTRY_IMAGE }}:latest
              ${{ env.REGISTRY_IMAGE }}:1.0 





