name: Push commit
on:
    workflow_dispatch:
    push:
      branches:
        - dev_0.3

permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Haldir65'
          git config --global user.email 'mjw090608@users.noreply.github.com'
          git checkout -b auto_merge
          git add .
          git commit -am "Automated report"
          git push --set-upstream origin auto_merge