name: Publish image to Docker hub
on:
    workflow_dispatch:
    push:
        branches:
            - publish_docker_image_to_ghcr

jobs:
    testing_image:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: inspect
          run: |
            docker run ghcr.io/haldir65/upgraded-train:sha-b7deb27

       